### ISSUE TITLE
`linc build` throws an UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by Sandyman** [bitgenics/linc-build-ssr#2]
I ran `linc init` on a new project, selected the new (only) profile 'Generic React', then ran `linc build`. It threw the following error: 

```
Using build profile: linc-profile-generic-react
(node:11440) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: ENOENT: no such file or directory, open '/home/sander/github/talk-resources/which-chris-html/dist/server-strategy.js'
(node:11440) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
`linc-cli` version 1.4.0
`linc-profile-generic-react` version 0.9.7
`node` version 8.4.0 (also happens on 8.7.0)

**Comment by evanderkoogh** [comment]
Yup.. we do not support not having router. I will add that support. And then have a proper try/catch around it as well.
